// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func TopBar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"bg-white border-b\"><div class=\"container mx-auto px-4 py-4\"><div class=\"flex justify-between items-center\"><div class=\"text-2xl font-bold\">Logo</div><nav><ul class=\"flex space-x-4\"><li><a href=\"#\" class=\"inline-block rounded-md px-3 py-1 text-gray-600 hover:text-gray-900 bg-gray-200 hover:bg-gray-300\">Dashboard</a></li><li><form action=\"/logout\" method=\"post\" class=\"m-0 p-0\"><button type=\"submit\" class=\"inline-block rounded-md px-3 py-1 text-red-600 hover:text-red-900 bg-red-200 hover:bg-red-300\">Logout</button></form></li></ul></nav></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
